"""empty message

Revision ID: 3fb42c728b34
Revises: 
Create Date: 2018-08-10 09:05:06.673334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb42c728b34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('phone_num', sa.String(length=11), nullable=False),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apply',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('stu_num', sa.String(length=8), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('introduction', sa.String(length=60), nullable=False),
    sa.Column('skill', sa.Text(), nullable=False),
    sa.Column('want_learn', sa.Text(), nullable=False),
    sa.Column('think_celitea', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.String(length=20), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('create_time')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_title', sa.String(length=30), nullable=False),
    sa.Column('article', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('apply')
    op.drop_table('user')
    # ### end Alembic commands ###
